version: 2.1

parameters:
  tag:
    type: string
    default: v1

jobs:
  vue-build:
    docker:
      - image: cimg/node:20.5.0
    working_directory: ~/frontend
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build frontend
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  vue-docker-build-and-push:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/frontend
    steps:
      - checkout
      - attach_workspace:
          at: ~/frontend
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            echo "Using TAG << pipeline.parameters.tag >>"
            docker build -t $DOCKERHUB_USERNAME/mlfront:<< pipeline.parameters.tag >> .
      - run:
          name: Push Vue Docker image
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_USERNAME/mlfront:<< pipeline.parameters.tag >>

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - vue-build:
          filters:
            branches:
              only:
                - develop
      - vue-docker-build-and-push:
          requires:
            - vue-build
          filters:
            branches:
              only:
                - develop
