apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress-v{version}
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - monthlylife.kro.kr
    secretName: ml-front-tls-secret
  rules:
  - host: monthlylife.kro.kr 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-svc-v{version}
            port:
              number: 80
